# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_ss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField()),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('user_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Usertwo')),
            ],
            options={
                'ordering': ['-datatime'],
            },
        ),
        migrations.CreateModel(
            name='comment_ss_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField()),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment_s.comment_ss')),
                ('user_normal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Usertwo')),
            ],
            options={
                'ordering': ['-datatime'],
            },
        ),
    ]
