# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_s', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_ss',
            options={'ordering': ['-datatime'], 'verbose_name': '\u4e00\u7ea7\u8bc4\u8bba', 'verbose_name_plural': '\u4e00\u7ea7\u8bc4\u8bba'},
        ),
        migrations.AlterModelOptions(
            name='comment_ss_s',
            options={'ordering': ['-datatime'], 'verbose_name': '\u4e8c\u7ea7\u8bc4\u8bba', 'verbose_name_plural': '\u4e8c\u7ea7\u8bc4\u8bba'},
        ),
        migrations.AlterField(
            model_name='comment_ss',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='comment_ss',
            name='question_content',
            field=models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='comment_ss',
            name='user_normal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Usertwo', verbose_name='\u8bc4\u8bba\u8005'),
        ),
        migrations.AlterField(
            model_name='comment_ss_s',
            name='reply_content',
            field=models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='comment_ss_s',
            name='reply_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment_s.comment_ss', verbose_name='\u8bc4\u8bba\u7684\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='comment_ss_s',
            name='user_normal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Usertwo', verbose_name='\u8bc4\u8bba\u7528\u6237'),
        ),
    ]
