# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='j_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='\u8282\u6807\u9898')),
                ('text', models.TextField(verbose_name='\u5185\u5bb9')),
                ('ordernum', models.PositiveIntegerField(verbose_name='\u8282\u5e8f\u53f7')),
                ('readcount', models.PositiveIntegerField(default=0, verbose_name='\u9605\u8bfb\u6570')),
            ],
            options={
                'ordering': ['ordernum'],
                'verbose_name': '\u8282',
                'verbose_name_plural': '\u8282',
            },
        ),
        migrations.CreateModel(
            name='z_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='\u7ae0\u6807\u9898')),
                ('text', models.TextField(verbose_name='\u5185\u5bb9')),
                ('ordernum', models.PositiveIntegerField(verbose_name='\u7ae0\u5e8f\u53f7')),
                ('readcount', models.PositiveIntegerField(default=0, verbose_name='\u9605\u8bfb\u6570')),
            ],
            options={
                'ordering': ['ordernum'],
                'verbose_name': '\u7ae0',
                'verbose_name_plural': '\u7ae0',
            },
        ),
        migrations.AddField(
            model_name='j_title',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach_blog.z_title', verbose_name='\u5206\u7c7b--\u7ae0\u540d\u79f0--\u7ae0\u5e8f\u53f7'),
        ),
    ]
