# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('activates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_bases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activates.Activate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Usertwo')),
            ],
            options={
                'ordering': ['-comment_time'],
            },
        ),
    ]
